# Generated by Django 4.0.3 on 2022-03-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('pwd', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('bdate', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('cmnd', models.CharField(max_length=15)),
                ('bienso', models.CharField(max_length=10)),
                ('anhbien', models.CharField(max_length=255)),
                ('sogiayto', models.CharField(max_length=255)),
                ('anhgiayto1', models.CharField(max_length=255)),
                ('anhgiayto2', models.CharField(max_length=255)),
                ('anhxe', models.CharField(max_length=255)),
            ],
        ),
    ]
