# Generated by Django 4.0.3 on 2022-04-16 09:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='anhbien',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='customer',
            name='anhgiayto1',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='customer',
            name='anhgiayto2',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='customer',
            name='anhxe',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RenameModel(
            old_name='Device',
            new_name='Gate',
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to=None)),
                ('imgtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('bienso', models.CharField(max_length=10)),
                ('id_cus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.customer')),
                ('id_gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.gate')),
            ],
        ),
        migrations.CreateModel(
            name='Cam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to=None)),
                ('imgtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('bienso', models.CharField(max_length=10)),
                ('id_gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.gate')),
            ],
        ),
    ]
