# Generated by Django 4.0.3 on 2022-04-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_customer_anhgiayto1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avt',
            field=models.ImageField(blank=True, upload_to='static/image'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bienso',
            field=models.CharField(max_length=15),
        ),
    ]
