# Generated by Django 4.0.3 on 2022-04-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_customer_avt_alter_customer_bienso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='anhxe',
            field=models.ImageField(blank=True, upload_to='static/image'),
        ),
    ]
