# Generated by Django 4.0.3 on 2022-04-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_customer_sogiayto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bienso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bienso', models.CharField(max_length=20)),
            ],
        ),
    ]
