# Generated by Django 4.0.3 on 2022-04-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_parking_id_cus_alter_parking_id_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bienso',
            name='bienso',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cam',
            name='bienso',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='anhbien',
            field=models.ImageField(blank=True, upload_to='static/image/bks'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='anhxe',
            field=models.ImageField(blank=True, upload_to='static/image/xe'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='avt',
            field=models.ImageField(blank=True, upload_to='static/image/people'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='bienso',
            field=models.CharField(max_length=15),
        ),
    ]
