# Generated by Django 4.0.3 on 2022-04-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_bienso_bienso_alter_cam_bienso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='id_gate',
            field=models.IntegerField(),
        ),
    ]
