# Generated by Django 4.0.3 on 2022-04-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_cam_id_gate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cam',
        ),
    ]
