# Generated by Django 4.0.3 on 2022-04-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_delete_cam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gate', models.IntegerField()),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('imgtime', models.DateTimeField()),
                ('bienso', models.CharField(max_length=15)),
            ],
        ),
    ]
