# Generated by Django 4.0.3 on 2022-04-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_cam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bienso',
        ),
    ]
