# Generated by Django 4.0.3 on 2022-04-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_delete_bienso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bienso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bienso1', models.CharField(max_length=15)),
                ('bienso2', models.CharField(max_length=15)),
            ],
        ),
    ]
