# Generated by Django 4.0.3 on 2022-04-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_bienso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parking',
        ),
    ]
