# Generated by Django 4.0.3 on 2022-04-26 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_delete_parking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cus', models.IntegerField()),
                ('id_gate', models.IntegerField()),
                ('imgtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('bienso', models.CharField(max_length=15)),
            ],
        ),
    ]
